### ISSUE TITLE
Issue in pattern matching

### ISSUE THREAD

**Issue by Jessewb786** [jmongard/Git.SemVersioning.Gradle#10]
I'm currently trying to get the following template to work to update the minor version

**The configuration for semver is:**

```
semver {
	defaultPreRelease = "snapshot"
	minorPattern = "^(\\s?)feat(?:\\(\\w+\\))?:"
	patchPattern = "^(\\s?)fix(?:\\(\\w+\\))?:"
}
```

The commit template I'm trying to match looks like:

```
TTLFLCT-1

feat: added git-semver-plugin for automatic semantic versioning
```

**The testing:**

When I pull your code and try this in the testCommits test in GitProviderTest, then the minor version updates correctly.
So it passes the unit test.

```
 val gitProvider = GitProvider(SemverSettings().apply {
         groupVersionIncrements = true
         minorPattern = "^(\\s?)feat(?:\\(\\w+\\))?:"
 })
 ...
 commit(it, "TTLFLCT-1\n\nfeat: a feature", gitProvider)
```

<img width="336" alt="Screen Shot 2021-11-10 at 18 31 07" src="https://user-images.githubusercontent.com/2103730/141163438-8284c701-6972-44f5-be1e-522eecd750cb.png">

If I try this in my actual project, then the minor version does not update.

<img width="588" alt="Screen Shot 2021-11-10 at 18 32 53" src="https://user-images.githubusercontent.com/2103730/141163815-8eb95d8d-9e86-44c1-8f2f-e5a0494de345.png">

<img width="388" alt="Screen Shot 2021-11-10 at 18 32 03" src="https://user-images.githubusercontent.com/2103730/141163552-bb3a15cc-2a41-415d-a997-e1a109542527.png">

This was tested on **Mac OS**.

**Comment by jmongard** [comment]
Example repository: https://github.com/jmongard/Git.SemVersioning.Gradle.Actions-Example/tree/custom-pattern

**Comment by Jessewb786** [comment]
@jmongard Sorry, you're absolutely right.

I had the configuration after the version assignment.
It now seems to work as intended.
