### ISSUE TITLE
`releaseVersion` should print / log the name of the (local) tag it created

### ISSUE THREAD

**Issue by sschuberth** [jmongard/Git.SemVersioning.Gradle#25]
The title says it all :-) That would help to know which tag to push afterwards.

**Comment by jmongard** [comment]
Version 0.6.0 now prints name of created tag like this:

`New tag: 0.39.1`

Would you have preferred just the tag name without the "New tag: " text when running in quiet mode?

**Comment by sschuberth** [comment]
> Would you have preferred just the tag name without the "New tag: " text when running in quiet mode?

No, that's fine. What counts is to see the version at all. Thanks!
