### ISSUE TITLE
buildSrc conventions style example

### ISSUE THREAD

**Issue by sebeard** [jmongard/Git.SemVersioning.Gradle#3]
Hi 

Great plugin and really simple to configure up.

I have a question or query as I'm struggling to get the versioning quite right in a multi-module project that is configured using Gradle 6's convention style plugins in the buildSrc directory. Do you have an example working with this?

I effectively have the following structure in buildSrc;
- `project-conventions.gradle`
- `library-conventions.gradle`

I apply the semantic versioning plugin in `project-conventions.gradle` and apply that to the root `build.gradle`

```
plugins {
    id 'com.github.jmongard.git-semver-plugin'
}

semver {
    //Example of each property with their respective default value
    defaultPreRelease = "SNAPSHOT"
    releasePattern = "\\Arelease(?:\\(\\w+\\))?:"
    majorPattern = "\\A\\w+(?:\\(\\w+\\))?!:|^BREAKING[ -]CHANGE:"
    minorPattern = "\\ANew Feature(?:\\(\\w+\\))?:"
    patchPattern = "\\AFix(?:\\(\\w+\\))?:"
    releaseCommitTextFormat = "Applying this commit will tag the release: %s\n\n%s"
    releaseTagNameFormat = "v%s"
    groupVersionIncrements = true
}

version semver.version
```

Each submodule has `library-conventions.gradle` applied. `project-conventions.gradle` also applies `library-conventions.gradle`

I was hoping that submodules would pick up on that version property but they don't seem to be. 

Happy to provide an example repository if that's helpful?

Many thanks.

**Comment by jmongard** [comment]
Hi

The version property in gradle is per project. Just use `allprojects` in project-convetions.gradle and it should work.
Don't apply the plugin to every sub project (though it will probably work) because that will cause the version to be calculated many times. 

**/buildsrc/src/main/groovy/project-conventions.gradle**
```
plugins {
    id "com.github.jmongard.git-semver-plugin"
}

semver {
  ...
}

allprojects {
    version = semver.version
}
```

**/buildsrc/build.gradle**
```
plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
}

dependencies {
    implementation "gradle.plugin.com.github.jmongard.git-semver-plugin:git-semver-plugin:0.2.0"
}
```

**/build.gradle**
```
plugins {
    id 'temp2.java-project-conventions'
}
```

In my private multi project repository using Gradle 6 convention style plugins I have just added the version plugin directly to the root build.gradle. 

**/build.gradle**
```
plugins {
    id "com.github.jmongard.git-semver-plugin" version "0.2.0"
}

allprojects {
    version = semver.version
}
```

Regards

**Comment by sebeard** [comment]
Ah great! That's the ticket - was just missing the `allProjects` closure wrapping it. Perfect thanks.

> Don't apply the plugin to every sub project (though it will probably work) because that will cause the version to be calculated many times.

Haha Yep did this. Lot of deleting of tags later got back to fresh :) 

Thanks again.
