### ISSUE TITLE
Dog-food this plugin to create release notes on GitHub

### ISSUE THREAD

**Issue by sschuberth** [jmongard/Git.SemVersioning.Gradle#38]
This project should use itself to create releases on GitHub with release notes attached 😀

**Comment by jmongard** [comment]
Yes, I have thought about it. I have been testing it out in some private repositories so now Is a good time to add it here as well.

**Comment by jmongard** [comment]
[It works 😄 ](https://github.com/jmongard/Git.SemVersioning.Gradle/releases/tag/v0.8.2)

**Comment by sschuberth** [comment]
"Pharma RexServer 0.8.2" sounds wrong, though 😉

**Comment by jmongard** [comment]
Indeed it is 😃. Should not be so fast when I copy past stuff.
