### ISSUE TITLE
Set the Gradle plugin portal page as the homepage

### ISSUE THREAD

**Issue by sschuberth** [jmongard/Git.SemVersioning.Gradle#39]
Under "About" -> "Website" for this GitHub project, link to https://plugins.gradle.org/plugin/com.github.jmongard.git-semver-plugin for convenience.

**Comment by jmongard** [comment]
Good idea. It is not very obvious that you can click the release version banner picture to take you there.

**Comment by jmongard** [comment]
Not sure why it did not work. Edited and saved the about page and now it works
