### ISSUE TITLE
Latest Published Version Mismatch

### ISSUE THREAD

**Issue by EverettZ** [jmongard/Git.SemVersioning.Gradle#47]
The latest release version, 0.11.0, doesnt appear to be published to https://plugins.gradle.org/m2/ despite the gradle site desplaying it as latest.

https://plugins.gradle.org/m2/gradle/plugin/com/github/jmongard/git-semver-plugin/git-semver-plugin/

**Comment by jmongard** [comment]
Version 0.11.0 is located here: https://plugins.gradle.org/m2/com/github/jmongard/git-semver-plugin/

The change of location was caused by an update to the gradle plugin publish plugin where the default location were changed.
