### ISSUE TITLE
Having a commit message title with a liternal HTML tag name breaks the release notes layout

### ISSUE THREAD

**Issue by sschuberth** [jmongard/Git.SemVersioning.Gradle#48]
Having a commit message like [this](https://github.com/oss-review-toolkit/ort/commit/3f4073f858fd407364409746cb6e802a3aff334c)

    `feat(reporter): Use <pre> block for issue messages`

results in release notes being rendered like [this](https://github.com/oss-review-toolkit/ort/releases/tag/13.0.0)

![image](https://github.com/jmongard/Git.SemVersioning.Gradle/assets/349154/f82968ea-c66e-47d6-9b9d-a0519cff7ddc)

because the `<pre>` is taken literally and being interpreted as a render action.

**Comment by jmongard** [comment]
I modified the change log formater to add a \ before every <. I hope this solves the issue with html in the texts

**Comment by sschuberth** [comment]
Confirmed to be fixed with release 0.12.0.

**Comment by sschuberth** [comment]
I'm reopening this as the implemented escaping is now too eager: Its also escapes `<` contained in backticks, see e.g. this [release](https://github.com/oss-review-toolkit/ort/releases/tag/15.3.0):

![image](https://github.com/jmongard/Git.SemVersioning.Gradle/assets/349154/976584bd-a1e6-4e4d-a3e7-3a89214ae627)

with the original commit title being rendered as

![image](https://github.com/jmongard/Git.SemVersioning.Gradle/assets/349154/2c56c8c6-5957-467e-a8bf-5bf4e7968724)

and the literal [patch](https://github.com/oss-review-toolkit/ort/commit/7b6537de397ace63c03bc71b63fa5984cadbdfaa.patch) including backticks:

![image](https://github.com/jmongard/Git.SemVersioning.Gradle/assets/349154/d3109430-2658-4aa5-894f-f744d1cd1265)

**Comment by jmongard** [comment]
It should now support `` `<html>` `` and ``` ``<html>`` ``` but not tripple back ticks.  I guess it is possible to do the code smarter to handle it but maybe it is not worth the effort.

**Comment by jmongard** [comment]
The plugin should now be able to support any number of `````````` `back ticks` ``````````
