### ISSUE TITLE
Ignore auto-version bumping on some commits

### ISSUE THREAD

**Issue by szhem** [jmongard/Git.SemVersioning.Gradle#5]
Hello,

Is it possible to configure the plugin somehow to ignore version bumping on some commit message patterns?
According to 
![image](https://user-images.githubusercontent.com/1523889/123930221-360cd880-d998-11eb-9929-082a8ebac9bd.png)
it can be useful to prevent auto-bumping on certain commit types, like the following
```
docs(scope): improving readme.md
style(scope): reformatting the code
```

**Comment by jmongard** [comment]
It is currently not possible to prevent auto bumping the version. The plug-in assumes you are working on the next release after tagging a commit with a version number and that the next release will contain new fixes or features. Auto bumping is made so you don't accidentally add changes to already released code without changing the version number.

Changing this behavior with a new option should be an easy fix but I won't be able to implement it for a few weeks.

**Comment by jmongard** [comment]
Hi,

I added an option in version 0.4.0 of the plugin to prevent automatic increment of the version for non `fix, feat, and breaking changes` commits.
```
semver {
    noAutoBumb = true
}
```

I hope this will help.

**Comment by szhem** [comment]
@jmongard Thanks a lot for the changes! It's what I needed.
