### ISSUE TITLE
Release 0.12.0 removes  `isPreRelease` from `SemVer`, making it a breaking change

### ISSUE THREAD

**Issue by sschuberth** [jmongard/Git.SemVersioning.Gradle#51]
In `SemVer` we used to have

    val isPreRelease
        get() = preRelease.isPreRelease

which is gone now. Was this intended? I was actually using this property, so version 0.12.0 is a breaking release (requiring a major version bump) for me.

**Comment by sschuberth** [comment]
Now I need to call `preRelease.isPreRelease`, which looks awkward. (Why should a pre-release not be a pre-release?)

**Comment by jmongard** [comment]
Yes, that would be ugly. Ill just add it back again. It got lost when I split the SemVersion class into three.

**Comment by sschuberth** [comment]
> Yes, that would be ugly. Ill just add it back again. It got lost when I split the SemVersion class into three.

Thanks. When you do a new release, please include https://github.com/jmongard/Git.SemVersioning.Gradle/pull/52 as well 😉

**Comment by jmongard** [comment]
It should be back now in 0.12.2
