### ISSUE TITLE
Can't get commit hash in version string

### ISSUE THREAD

**Issue by edzaffirm** [jmongard/Git.SemVersioning.Gradle#53]
I'm using version 0.12.2 of the plugin. 

When I print `semver.semVersion.toString()` in my `build.gradle.kts` file, the result doesn't include the commit hash, even though `./gradlew printSemVersion` does.

When I try to call `semver.semVersion.toInfoVersionString`, my IDE thinks that the `toInfoVersionString` method doesn't exist.

These are the settings I've applied:
```
semver {
    releaseTagNameFormat = "v%s"
    createReleaseCommit = false
}
```

Any help would be appreciated. Thanks for the great work on the plugin!

**Comment by jmongard** [comment]
While updating the plugin to work with Gradle's configuration cache, I divided the original SemVersion class into three parts. This was done to avoid triggering Gradle's configuration change detection if the version number remained the same.

Unfortunately, I mistakenly moved the implementation containing the SHA property and toInfoVersionString method to a new property. To fix this, I've reverted to the original property name in version `0.12.3`.

Thanks for using the Plugin :-)
