### ISSUE TITLE
`printChangelog --file` doesn't create parent directory for the specified file

### ISSUE THREAD

**Issue by tacascer** [jmongard/Git.SemVersioning.Gradle#58]
The current logic doesn't support creating parent directories to the changelog file

https://github.com/jmongard/Git.SemVersioning.Gradle/blob/master/src/main/kotlin/git/semver/plugin/gradle/PrintTask.kt#L26-L28

**Comment by jmongard** [comment]
Do you think adding a mkdir call would solve your issue?

**Comment by tacascer** [comment]
In Kotlin I would do something like this
https://github.com/tacascer-org/xml-processor/blob/main/src/main/kotlin/io/github/tacascer/XmlFilter.kt#L45-L49

**Comment by jmongard** [comment]
This should be working now in 0.12.8.
